name: Deploy Assets to CDN

on:
  push:
    paths:
      - 'assets/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Optimize and deploy assets
      run: node tools/deploy-assets.js
      env:
        CDN_BASE_URL: ${{ secrets.CDN_BASE_URL }}
    
    - name: Deploy to Vercel
      uses: vercel/action@v1
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        working-directory: ./assets
    
    - name: Commit updated manifest
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add assets/manifest.json
        git diff --staged --quiet || git commit -m "Update asset manifest [skip ci]"
        git push
