name: Deploy Assets to CDN

on:
  push:
    paths:
      - 'assets/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Optimize assets
      run: node tools/deploy-assets.js
      env:
        CDN_BASE_URL: ${{ secrets.CDN_BASE_URL || 'https://displace-plugin-assets.vercel.app' }}
    
    - name: Deploy assets to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./assets
        vercel-args: '--prod'
        
    - name: Update manifest with CDN URL
      run: |
        # Update manifest.json with actual Vercel URL
        VERCEL_URL="${{ secrets.CDN_BASE_URL || 'https://displace-plugin-assets.vercel.app' }}"
        sed -i "s|https://your-cdn.vercel.app/assets|$VERCEL_URL|g" assets/manifest.json
        
    - name: Commit updated manifest
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "GitHub Actions Bot"
        git add assets/manifest.json
        if git diff --staged --quiet; then
          echo "No changes to manifest.json"
        else
          git commit -m "🤖 Update asset manifest with CDN URLs [skip ci]"
          git push
        fi
